### ISSUE TITLE
[feature request] Add all nodes into default nodepool when yurt-app-manager setups

### ISSUE THREAD

**Issue by Congrool** [openyurtio/yurt-app-manager#31]
**What would you like to be added**:
I saw that `yurt-app-manager` has the option `--create-default-pool`, whose default value is false. When we set it true, `yurt-app-manager` will create two nodepools called `default-nodepool` and `default-edge-nodepool` with no node in them. 

How about adding all cloud nodes into `default-pool` and all edge nodes into `default-edge-nodepool` when yurt-app-manager setups? And also set the default value of `--create-default-pool` to true.  When new nodes join the cluster, we can also allocate it to the default `nodepool` without the awareness of users.

**Why is this needed**:
With this feature, other components depending on `nodepool` can have a good assumption that each node belongs to one nodepool. Thus, these components can handle nodepool nodes and non-nodepool nodes in a consistent way.

It seems that doing so doesn't have any effect on components which don't need `nodepool` resource, and users can simply overwrite the label to allocate a node to another custom nodepool. It works like the default namespace.

And I think components like `raven` will benefit from it, which has to have one gateway node in each nodepool.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@Congrool I think it's not a good idea to add node into default NodePool, because edge node should be added to which nodePool, end user must have clear consideration, we can not handle it in a quiet mode.

**Comment by rambohe-ch** [comment]
@Congrool I will close this issue because we have plan to support this feature. and you can feel free to reopen this issue when you need.
