### ISSUE TITLE
[feature request] bump apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by SataQiu** [openyurtio/yurt-app-manager#43]
**What would you like to be added**:

**Why is this needed**:
As https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122 mentioned:

The `apiextensions.k8s.io/v1beta1` API version of CustomResourceDefinition is no longer served as of v1.22.
We should migrate manifests and API clients to use the `apiextensions.k8s.io/v1` API version, available since v1.16.

Ref: https://github.com/openyurtio/yurt-app-manager/blob/5dc7d07355df12cd63ebc3cb7692f601a932b7a1/config/setup/all_in_one.yaml#L1

Ref: openyurtio/yurtcluster-operator#25

**others**
/kind feature

**Comment by huiwq1990** [comment]
@rambohe-ch this issue is already solved.
