### ISSUE TITLE
[BUG] yurt-app-manager samples directory not found

### ISSUE THREAD

**Issue by tongchao199** [openyurtio/yurt-app-manager#45]
**What happened**:

config/yurt-app-manager/samples/ directory not found

doc index
  - https://github.com/openyurtio/yurt-app-manager/blob/master/docs/yurt-app-manager-tutorial.md#how-to-use

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@tongchao199 you can reference the following link to get tutorials of yurt-app-manager:
https://openyurt.io/docs/core-concepts/yurt-app-manager
https://openyurt.io/docs/user-manuals/workload/node-pool-management
https://openyurt.io/docs/user-manuals/workload/yurt-app-set
https://openyurt.io/docs/user-manuals/workload/yurt-app-daemon
