### ISSUE TITLE
[BUG] support k8s 1.22 

### ISSUE THREAD

**Issue by ujnzxw** [openyurtio/yurt-app-manager#63]
**What happened**:
We announced supporting Kubernetes version 1.22， but the deployment file all_in_one.yaml and the container image openyurt/yurt-app-manager:v0.5.0 are not updated.
In addition， the related document is not updated yet.
**What you expected to happen**:
support k8s v1.22 officially.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy yurt-app-manager following the official document.
**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v0.6.1-beta.1
- Kubernetes version (use `kubectl version`): 1.22.11
- OS (e.g: `cat /etc/os-release`): Centos 7.0
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@ujnzxw Thank you for raising issue. Would you like to take over and solve this problem?
