### ISSUE TITLE
[unit test] improve unit test coverage for yurtappset 

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/yurt-app-manager#74]
**What would you like to be added**:
improve unit test coverage for yurtappset controller:

target coverage: 70%

**Why is this needed**:
improve unit test coverage for OpenYurt project.

**others**
/kind feature

**Comment by Congrool** [comment]
We commented tests files under `pkg/yurtappmanager/controller/yurtappset` in pr #72, including
- revision_test.go
- yurtappset_controller_statefulset_test.go
- yurtappset_controller_test.go
- yurtappset_controller_suite_test.go 

We'd better take care of these tests in this pr.

**Comment by rambohe-ch** [comment]
Fixes by #113
