### ISSUE TITLE
[API upgrade] upgrade version from v1alpha1 to v1beta1 for NodePool kind

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/yurt-app-manager#77]
**What would you like to be added**:
1. resource API upgrade: NodePool kind
2. present OpenYurt resource API on the homepage website in order to make end users to get them easily.

**Why is this needed**:
NodePool resource is widely used in OpenYurt project, and we recommend to upgrade its version to v1beta1 strongly.

**others**
/kind feature

**Comment by huiwq1990** [comment]
@rambohe-ch should we change the storageversion to v1beta1? If we change it, user should migrate v1alpha1 version resources.

**Comment by rambohe-ch** [comment]
> @rambohe-ch should we change the storageversion to v1beta1? If we change it, user should migrate v1alpha1 version resources.

@huiwq1990 how about use v1alpha1 to store resource at first

**Comment by rambohe-ch** [comment]
The issue was fixed by #104
