### ISSUE TITLE
[feature request] refactor webhook implementation

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/yurt-app-manager#78]
**What would you like to be added**:
- upgrade controller-manager version `sigs.k8s.io/controller-runtime v0.10.3`
- use SetupWebhookWithManager implement webhook, as https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html

**Why is this needed**:

- it's easy write webhook unit test
- reduces maintenance costs

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@huiwq1990 agree+1

**Comment by rambohe-ch** [comment]
The issue was fixed by #88
