### ISSUE TITLE
[feature request] push ci docker image to repo

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/yurt-app-manager#91]
**What would you like to be added**:
1) Build latest master branch's docker image, and push it to docker.io, just like https://github.com/openebs/lvm-localpv/blob/develop/.github/workflows/build.yml#L130.
2) recommend users use chart install yurt-app-manager

**Why is this needed**:
If users want to experience latest yurt-app-manager, they should build the image themself. And users report yurt-app-manager's bugs could be solved by it.   https://github.com/openyurtio/yurt-app-manager/issues/90

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@huiwq1990 The ability to periodically build yurt-app-manager image has been implemented, you can reference link here: https://github.com/openyurtio/yurt-app-manager/blob/master/.github/workflows/release.yaml

**Comment by rambohe-ch** [comment]
@huiwq1990 pull request #93 has been merged, so i will close this issue.
